plugins {
    alias(libs.plugins.android.test)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.androidx.baselineprofile)
}

/**
 * Generates the baseline profile for :app (PERF-3).
 *
 * Not a normal library module: `com.android.test` produces a test-only APK that
 * drives the launcher on a device and records which classes and methods the critical
 * start-up path actually touches. The app then ships those as AOT compilation hints.
 *
 * The profile itself is NOT committed from a hand-written guess — it is generated by
 * running:
 *     ./gradlew :app:generateBaselineProfile
 * which CI's emulator job does. See .github/workflows/ci.yml.
 */
android {
    namespace = "com.example.minimallauncher.baselineprofile"
    compileSdk = 35

    defaultConfig {
        minSdk = 26
        targetSdk = 35
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    targetProjectPath = ":app"
    // The module instruments itself to collect the profile.
    experimentalProperties["android.experimental.self-instrumenting"] = true

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation(libs.androidx.test.ext.junit)
    implementation(libs.androidx.test.runner)
    implementation(libs.androidx.test.uiautomator)
    implementation(libs.androidx.benchmark.macro.junit4)
}
